id: P000670
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18181
  title: ཧི་མ་ལ་ཡའི་ཕར་ཚུར།
  author: ''
  volumes:
    0c8ecb435a104b14bdbe995ca1e6c5da:
      image_group_id: I8LS18191
      title: ''
      volume_number: 1
      total_pages: 235
